version: 2
updates:
- package-ecosystem: cargo
  directory: "/backend"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
- package-ecosystem: npm
  directory: "/frontend"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
- package-ecosystem: npm
  directory: "/nitro_repo-api-wrapper"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
