[package]
name = "nitro_repo"
version = "0.1.0"
authors = ["Wyatt Jacob Herkamp <wherkamp@kingtux.me>"]
edition = "2021"
build = "build.rs"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[package.metadata.deb]
depends = "$auto, systemd"
extended-description = "An open source artifact manager. Written in Rust back end and an React front end to create a fast and modern experience "
section = "admin"
priority = "optional"
assets = [
    ["target/release/nitro_repo", "usr/bin/nitro_repo", "755"],
    ["other/nitro_repo.service", "/lib/systemd/system/nitro_repo.service", "644"],
]

[dependencies]
# Web
actix = "0.13.0"
actix-web = { version = "4.0.0", features = ["openssl"] }
actix-cors = "0.6.0"
actix-service = "2.0.1"
actix-multipart = "0.4.0"
openssl = { version = "0.10", features = ["v110"], optional = true }
actix-files = "0.6.0"
# Partly Web
lettre = "0.10.0-rc.4"
# Database
diesel = { version = "1.4.8", features = ["mysql", "r2d2"] }
diesel_migrations = "1.4.0"
r2d2 = "0.8.9"
r2d2_mysql = "*"
# Config
dotenv = "0.15.0"
# Serde
serde = { version = "1.0.130", features = ["derive"] }
serde_json = "1.0.71"
futures = "0.3.17"
serde-xml-rs = "0.5.1"
serde_yaml = { version = "0.8.21" }
toml = "0.5.8"

# utils
rand = "0.8.4"
rand_core = { version = "0.6.3", features = ["std"] }
rust-embed = { version = "6.2.0", features = ["interpolate-folder-path"] }
argon2 = "0.3.1"
chrono = "0.4.19"
regex = "1.5.4"
glob = "0.3.0"
futures-util = "0.3.17"
time = "0.3.5"
base64 = "0.13.0"
tokio = "1.14.0"

# Log
nitro_log = { git = "https://github.com/wherkamp/nitro_log", features = ["time", "colors"] }
log = "0.4.14"
# Rust Internal
strum = { version = "0.24.0", features = ["derive"] }
strum_macros = "0.24.0"
derive_more = "0.99.14"
async-trait = "0.1.51"
thiserror = "1.0.30"
anyhow = "1.0.56"
# Badge Stuff
badge-maker = "0.2.0"
usvg = "0.22.0"
resvg = "0.22.0"
tiny-skia = "0.6.1"
# Webhook
webhook = "2.0.0"
zip = "0.5.13"
# Installer
tui = "0.17"
crossterm = "0.22"
clap = { version = "3.1.6", features = ["derive"] }
unicode-width = "0.1.9"
[build-dependencies]
zip = "0.5.13"
walkdir = "2.3.2"
[features]
default = ["frontend"]
# Defines a feature named `webp` that does not enable any other features.
ssl = ["openssl", "actix-web/openssl"]
dev-frontend = []
frontend = []
