disallowed-types = [
    { path = "std::collections::HashMap", reason = "use ahash::HashMap" },
    { path = "std::collections::HashSet", reason = "use ahash::HashSet" },
    { path = "std::sync::Mutex", reason = "use parking_lot::Mutex" },
    { path = "std::sync::RwLock", reason = "use parking_lot::RwLock" },
]
