version: "3.9"
services:
  nitro_repo:
    image: nitro_repo:1.1.0
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "6742:6742"
    volumes:
      - nitro_repo-data:/app/data
    restart: unless-stopped
    stdin_open: true
    tty: true
volumes:
  nitro_repo-data: { }