[package]
name = "nitro_repo"
version = "1.0.0"
authors = ["Wyatt Jacob Herkamp <wherkamp@kingtux.me>"]
edition = "2021"
build = "build.rs"
license-file = "../LICENSE"
[dependencies]
# Web
actix = "0.13.0"
actix-web = { version = "4.0.1", features = ["openssl"] }
actix-cors = "0.6.1"
actix-service = "2.0.2"
actix-multipart = "0.4.0"
openssl = { version = "0.10.40", features = ["v110"], optional = true }
actix-files = "0.6.0"
# Partly Web
lettre = "0.10.0-rc.6"
handlebars = "4.2.2"
# Database
diesel = { version = "1.4.8", features = ["mysql", "r2d2"] }
diesel_migrations = "1.4.0"
r2d2 = "0.8.9"
r2d2_mysql = "21.0.0"
# Serde
serde = { version = "1.0.137", features = ["derive"] }
serde_json = "1.0.81"
futures = "0.3.21"
serde-xml-rs = "0.5.1"
serde_yaml = "0.8.24"
toml = "0.5.9"

# utils
rand = "0.8.5"
rand_core = { version = "0.6.3", features = ["std"] }
rust-embed = { version = "6.4.0", features = ["interpolate-folder-path"] }
argon2 = "0.4.0"
chrono = "0.4.19"
regex = "1.5.5"
glob = "0.3.0"
futures-util = "0.3.21"
time = "0.3.9"
base64 = "0.13.0"
tokio = "1.18.1"
uuid = { version = "1.0.0", features = ["serde", "v4"] }
colored = "2.0.0"
# Log
nitro_log = { git = "https://github.com/wherkamp/nitro_log", features = ["time", "colors"] }
log = "0.4.17"
# Rust Internal
strum = { version = "0.24.0", features = ["derive"] }
strum_macros = "0.24.0"
derive_more = "0.99.17"
async-trait = "0.1.53"
thiserror = "1.0.31"
anyhow = "1.0.57"
either = "1.6.1"
# Badge Stuff
badge-maker = "0.2.1"
# Webhook
webhook = "2.0.0"
# Installer
tui = "0.18.0"
crossterm = "0.23.2"
clap = { version = "3.1.15", features = ["derive"] }
unicode-width = "0.1.9"

[build-dependencies]
vergen = "7.0.0"
[features]
ssl = ["openssl", "actix-web/openssl"]

