[package]
name = "nitro_repo"
version = "1.1.0-BETA"
authors = ["Wyatt Jacob Herkamp <wherkamp@kingtux.me>"]
edition = "2021"
build = "build.rs"
license-file = "../LICENSE"
default-run = "nitro_repo_full"

[lib]
name = "api"
path = "src/lib.rs"
[[bin]]
name = "nitro_repo_full"
required-features = ["multi_storage"]
[[bin]]
name = "simple_installer"

[dependencies]
# Web
actix-web = { version = "4.1", features = ["openssl", "cookies"] }
actix-cors = "0.6"
actix-service = "2.0"
openssl = { version = "0.10", features = ["v110"], optional = true }
actix-files = "0.6"
# Partly Web
lettre = "0.10.0"
handlebars = "4.3.2"
# Database
sea-orm = { version = "0.9", features = ["sqlx-mysql", "sqlx-sqlite", "runtime-actix-native-tls", "macros"] }
sqlx = "0.6"
# Serde
serde = { version = "1.0.139", features = ["derive"] }
serde_json = "1.0.82"
futures = "0.3.21"
serde-xml-rs = "0.5.1"
toml = "0.5.9"
# utils
rand = "0.8.5"
rust-embed = { version = "6.4.0", features = ["interpolate-folder-path"] }
argon2 = "0.4.1"
chrono = "0.4.19"
regex = "1.6.0"
futures-util = "0.3.21"
base64 = "0.13.0"
tokio = { version = "1.20.0", features = ["full"] }
uuid = { version = "1.1.2", features = ["serde", "v4"] }
style-term = "1.0.0"
mime_guess = "2.0.4"
paste = "1.0.7"
reqwest = { version = "0.11.11", features = ["stream"] }
bytes = "1.2.0"
tokio-stream = "0.1.9"
lockfree = "0.5.1"

# Log
nitro_log = { git = "https://github.com/wyatt-herkamp/nitro_log", features = ["chrono", "style-term"] }
log = { version = "0.4.17", features = ["kv_unstable", "kv_unstable_std", "kv_unstable_serde"] }
# Rust Internal
strum = { version = "0.24.1", features = ["derive"] }
strum_macros = "0.24.2"
async-trait = "0.1.56"
thiserror = "1.0.31"
anyhow = "1.0.58"
# Badge Stuff
badge-maker = "0.3.1"
# Webhook
webhook = "2.0.0"
# Installer
clap = { version = "3.2.12", features = ["derive"] }
semver = "1.0.12"
# Cache
redis = "0.21.5"
comrak = "0.14"
# Staging
tempfile="3.3.0"
git2 = "0.14.4"
[build-dependencies]
vergen = "7.0.0"
[features]
# The latest Updaters will always be under default features
default = ["updater_one-one", "multi_storage"]
ssl = ["openssl", "actix-web/openssl"]

multi_storage = []
# Updaters
# Updater for 1.0.0 - 1.1.0
updater_one-one = []
