[package]
name = "nitro_repo"
version = "1.1.0-BETA"
authors = ["Wyatt Jacob Herkamp <wherkamp@kingtux.me>"]
edition = "2021"
build = "build.rs"
license-file = "../LICENSE"
[dependencies]
# Web
actix = "0.13.0"
actix-web = { version = "4.0.0", features = ["openssl"] }
actix-cors = "0.6.0"
actix-service = "2.0.1"
actix-multipart = "0.4.0"
openssl = { version = "0.10", features = ["v110"], optional = true }
actix-files = "0.6.0"
# Partly Web
lettre = "0.10.0-rc.4"
handlebars = "4.2.2"
# Database
sea-orm = { version = "0.7.1", features = [ "sqlx-mysql","sqlx-sqlite", "runtime-actix-native-tls", "macros" ] }
sqlx ="0.5.13"
# Serde
serde = { version = "1.0.130", features = ["derive"] }
serde_json = "1.0.71"
futures = "0.3.17"
serde-xml-rs = "0.5.1"
serde_yaml = { version = "0.8.21" }
toml = "0.5.8"

# utils
rand = "0.8.4"
rand_core = { version = "0.6.3", features = ["std"] }
rust-embed = { version = "6.2.0", features = ["interpolate-folder-path"] }
argon2 = "0.4.0"
chrono = "0.4.19"
regex = "1.5.4"
glob = "0.3.0"
futures-util = "0.3.17"
time = "0.3.5"
base64 = "0.13.0"
tokio = "1.14.0"
uuid = { version = "0.8.2", features = ["serde", "v4"] }
colored = "2.0.0"
# Log
nitro_log = { git = "https://github.com/wherkamp/nitro_log", features = ["time", "colors"] }
log = "0.4.14"
# Rust Internal
strum = { version = "0.24.0", features = ["derive"] }
strum_macros = "0.24.0"
derive_more = "0.99.14"
async-trait = "0.1.51"
thiserror = "1.0.30"
anyhow = "1.0.56"
either = "1.6.1"
# Badge Stuff
badge-maker = "0.2.0"
# Webhook
webhook = "2.0.0"
# Installer
tui = "0.17"
crossterm = "0.23"
clap = { version = "3.1.6", features = ["derive"] }
unicode-width = "0.1.9"

[build-dependencies]
vergen = "7.0.0"
[features]
ssl = ["openssl", "actix-web/openssl"]

