[package]
name = "nitro_repo"
version = "1.0.2"
authors = ["Wyatt Jacob Herkamp <wherkamp@kingtux.me>"]
edition = "2021"
build = "build.rs"
license-file = "../LICENSE"
[dependencies]
# Web
actix-web = { version = "4.1.0", features = ["openssl"] }
actix-cors = "0.6.1"
actix-service = "2.0.2"
openssl = { version = "0.10.40", features = ["v110"], optional = true }
actix-files = "0.6.1"
# Partly Web
lettre = "0.10.0-rc.7"
handlebars = "4.3.1"
# Database
diesel = { version = "1.4.8", features = ["mysql", "r2d2"] }
diesel_migrations = "1.4.0"
r2d2 = "0.8.9"
r2d2_mysql = "21.0.0"
# Serde
serde = { version = "1.0.137", features = ["derive"] }
serde_json = "1.0.81"
serde-xml-rs = "0.5.1"
toml = "0.5.9"

# utils
rand = "0.8.5"
rand_core = { version = "0.6.3", features = ["std"] }
rust-embed = { version = "6.4.0", features = ["interpolate-folder-path"] }
argon2 = "0.4.0"
chrono = "0.4.19"
regex = "1.5.6"
futures-util = "0.3.21"
base64 = "0.13.0"
tokio = "1.19.2"
style-term = "1.0.0"
# Log
# Unstable Use git = "https://github.com/wherkamp/nitro_log"
nitro_log = { version = "1.0.1", features = ["chrono", "style-term"] }
log = "0.4.17"
# Rust Internal
strum = { version = "0.24.1", features = ["derive"] }
strum_macros = "0.24.1"
derive_more = "0.99.17"
async-trait = "0.1.56"
thiserror = "1.0.31"
anyhow = "1.0.57"
either = "1.6.1"
# Badge Stuff
badge-maker = "0.3.1"
# Webhook
webhook = "2.0.0"
# Installer
tui = "0.18.0"
crossterm = "0.24.0"
clap = { version = "3.2.1", features = ["derive"] }
unicode-width = "0.1.9"

[build-dependencies]
vergen = "7.1.0"
[features]
ssl = ["openssl", "actix-web/openssl"]

