[[settings]]
key = "installed"
name = "Installed"
type = "boolean"
properties = ["hidden"]
[[settings]]
key = "version"
name = "Version"
type = "string"
properties = ["hidden"]
[[settings]]
key = "email.host"
name = "SMTP Host"
type = "string"
default="example.com"
[[settings]]
key = "email.username"
name = "Email Username"
type = "string"
default="no-reply@example.com"
[[settings]]
key = "email.password"
name = "Email Password"
type = "string"
default=""
[[settings]]
key = "email.encryption"
name = "SMTP Encryption"
type = "string"
options = ["TLS", "NONE"]
default="NONE"
[[settings]]
key = "email.from"
name = "Mail From"
type = "string"
from=""
[[settings]]
key = "email.port"
name = "Mail Port"
type = "int"
default = "587"
[[settings]]
key = "name.public"
name = "Public Name"
type = "string"
default = "Nitro Repo"
public = true
[[settings]]
key = "description"
name = "Website Description"
type = "string"
default = "An open source artifact manager. Written in Rust back end and an Vue front end to create a fast and modern experience"
public = true
