name: Pull Request Javascript

on:
  pull_request:
    branches: master
env:
  CARGO_TERM_COLOR: always
jobs:
  build:
    if: contains(github.event.pull_request.labels.*.name, 'javascript')    
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          working-directory: frontend
          node-version-file: 'frontend/.nvmrc'
      - name: Install Site
        working-directory: frontend
        run: npm run ci-linklib && npm install
