name: Pull Request Javascript

on:
  pull_request:
    types: [ labeled ]

env:
  CARGO_TERM_COLOR: always
jobs:
  build:
    if: contains(github.event.pull_request.labels.*.name, 'javascript')    
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          working-directory: site
          node-version: 16.x
      - name: Install Site
        working-directory: site
        run: npm install
