name: Push

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          working-directory: site
          node-version: 16.x
      - name: Install Site
        working-directory: site
        run: npm install
      - uses: Swatinem/rust-cache@v1
      - name: Update Rust
        run: rustup update
      - name: Build
        run: sh build.sh
