name: Push and Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
env:
  CARGO_TERM_COLOR: always
jobs:
  build:
    name: Linux / Stable
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: Swatinem/rust-cache@v1
      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          working-directory: backend
          toolchain: stable
          override: true
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          working-directory: frontend
          node-version-file: 'frontend/.nvmrc'
      - name: Build API
        working-directory: nitro_repo-api-wrapper
        run: npm install && npm run build
      - name: Install Frontend
        working-directory: frontend
        run: npm install
      - name: Build
        run: sh build.sh ssl
      - name: Upload Artifact Linux
        uses: actions/upload-artifact@v2
        with:
          name: nitro_repo stable Linux
          path: nitro_repo.tar.gz
  clippy_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: Swatinem/rust-cache@v1
      - run: rustup component add clippy
      - uses: actions-rs/clippy-check@v1
        with:
          working-directory: backend
          token: ${{ secrets.GITHUB_TOKEN }}
          # Yes by doing this we are not checking the feature code. However, it is a small point. And I really dont want to have to run the build script
          args: --manifest-path backend/Cargo.toml --no-default-features
